Feature/9 prefetching records
wem/vertx-kinesis-consumer-orchestra pull request #15
Opened 2020-08-08 16:03 UTC by wem

2020-08-09 08:31 UTC, snakeru requested changes

2020-08-09 08:31 UTC, snakeru commented on src/main/kotlin/ch/sourcemotion/vertx/kinesis/consumer/orchestra/consumer/AbstractKinesisConsumerVerticle.kt
> +        recordFetcher.fetchNextRecords(positionToFetch, false)
Why no waiting? Does it brinch much?

2020-08-09 08:31 UTC, snakeru commented on src/main/kotlin/ch/sourcemotion/vertx/kinesis/consumer/orchestra/consumer/AbstractKinesisConsumerVerticle.kt
> -                    }
Unrelated comment: Michel, have you looked at my feedback for the previous (large) PR?

2020-08-09 08:31 UTC, snakeru commented on src/main/kotlin/ch/sourcemotion/vertx/kinesis/consumer/orchestra/consumer/AbstractKinesisConsumerVerticle.kt
> +                        }
This whole construct is somewhat hard to understand. We manipulate three positions (positionToFetch, nextPositionIfDeliveredSuccessful, positionAfterFailure) to calculate the fourth it seems and also start/stop fetching in the process. May be splitting this into some (possibly inlined) methods might help. Or may be an illustration to describe how these relate to each other.

--

BTW - why this whole store with re-fetching? What kind of failure scenario is envisioned?

2020-08-09 08:31 UTC, snakeru commented on src/main/kotlin/ch/sourcemotion/vertx/kinesis/consumer/orchestra/consumer/RecordFetcher.kt
> +     * refreshed by the [positionToFetch.sequenceNumber] and retried to fetch afterwards.
```suggestion
     * refreshed by the [positionToFetch.sequenceNumber] and fetch will be retried afterwards.
```

2020-08-09 08:31 UTC, snakeru commented on src/test/kotlin/ch/sourcemotion/vertx/kinesis/consumer/orchestra/consumer/RecordFetcherTest.kt
> +            SequenceNumber("sequence-number", SequenceNumberIteratorPosition.AFTER)
unexpected that AFTER constant is used to create a "previous" value.

2020-08-09 08:31 UTC, snakeru commented on src/test/kotlin/ch/sourcemotion/vertx/kinesis/consumer/orchestra/consumer/RecordFetcherTest.kt
> +    internal fun exception_case_restart_fetching(testContext: VertxTestContext) = asyncTest(testContext) {
even after reading this test I still can't understand the underlying logic. I think more a docsting or possibly refactoring is needed.

2020-08-09 08:31 UTC, snakeru commented on src/test/kotlin/ch/sourcemotion/vertx/kinesis/consumer/orchestra/consumer/RecordFetcherTest.kt
> +        assertFailsWith<RecordFetcher.WrongFetchingOrderException> {
Perhaps some default value is in effect? It is totally not clear why such sequence of actions should lead to an exception

2020-08-15 05:41 UTC, wem commented on src/main/kotlin/ch/sourcemotion/vertx/kinesis/consumer/orchestra/consumer/AbstractKinesisConsumerVerticle.kt
> +        recordFetcher.fetchNextRecords(positionToFetch, false)
As this is the first fetch, directly after the consumer is deployed. This way, we save time (default 1 second)

2020-08-21 17:39 UTC, wem commented on src/main/kotlin/ch/sourcemotion/vertx/kinesis/consumer/orchestra/consumer/AbstractKinesisConsumerVerticle.kt
> -                    }
As discussed via Slack that we merge it, no. I will catch up.

2020-08-21 17:49 UTC, wem commented on src/main/kotlin/ch/sourcemotion/vertx/kinesis/consumer/orchestra/consumer/AbstractKinesisConsumerVerticle.kt
> +                        }
Good point about the readability. Will refactor it. The orchestra has a configurable failure handling. Either the fetching will continue and ignores any kind of failure, or retries from the failed record (with the correct exception thrown and contains necessary information), or the records get re-fetched from Kinesis according the last used iterator. But the exception handling i plan to refactor. It works but i don't like it. Let us discuss about, ok?

2020-09-02 14:31 UTC, wem commented
Any objections should be done now.

2020-09-02 14:31 UTC, wem reviewed
Any objections should be done now.

2020-09-02 14:31 UTC, wem commented on src/test/kotlin/ch/sourcemotion/vertx/kinesis/consumer/orchestra/consumer/RecordFetcherTest.kt
> +        assertFailsWith<RecordFetcher.WrongFetchingOrderException> {
Yes there is an order. To get next records without fetching (on known position) makes no sense. We can also return a nullable result for sure, but this not explicit indicates a mistake. Basically this exception handling and test is especially to cover regressions.

2020-09-30 05:18 UTC, merged